// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gulimall-product/internal/gulimall_product/model"
)

func newPmsProductAttrValue(db *gorm.DB, opts ...gen.DOOption) pmsProductAttrValue {
	_pmsProductAttrValue := pmsProductAttrValue{}

	_pmsProductAttrValue.pmsProductAttrValueDo.UseDB(db, opts...)
	_pmsProductAttrValue.pmsProductAttrValueDo.UseModel(&model.PmsProductAttrValue{})

	tableName := _pmsProductAttrValue.pmsProductAttrValueDo.TableName()
	_pmsProductAttrValue.ALL = field.NewAsterisk(tableName)
	_pmsProductAttrValue.ID = field.NewInt64(tableName, "id")
	_pmsProductAttrValue.SpuID = field.NewInt64(tableName, "spu_id")
	_pmsProductAttrValue.AttrID = field.NewInt64(tableName, "attr_id")
	_pmsProductAttrValue.AttrName = field.NewString(tableName, "attr_name")
	_pmsProductAttrValue.AttrValue = field.NewString(tableName, "attr_value")
	_pmsProductAttrValue.AttrSort = field.NewInt32(tableName, "attr_sort")
	_pmsProductAttrValue.QuickShow = field.NewInt32(tableName, "quick_show")

	_pmsProductAttrValue.fillFieldMap()

	return _pmsProductAttrValue
}

type pmsProductAttrValue struct {
	pmsProductAttrValueDo

	ALL       field.Asterisk
	ID        field.Int64  // id
	SpuID     field.Int64  // 商品id
	AttrID    field.Int64  // 属性id
	AttrName  field.String // 属性名
	AttrValue field.String // 属性值
	AttrSort  field.Int32  // 顺序
	QuickShow field.Int32  // 快速展示【是否展示在介绍上；0-否 1-是】

	fieldMap map[string]field.Expr
}

func (p pmsProductAttrValue) Table(newTableName string) *pmsProductAttrValue {
	p.pmsProductAttrValueDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pmsProductAttrValue) As(alias string) *pmsProductAttrValue {
	p.pmsProductAttrValueDo.DO = *(p.pmsProductAttrValueDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pmsProductAttrValue) updateTableName(table string) *pmsProductAttrValue {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.SpuID = field.NewInt64(table, "spu_id")
	p.AttrID = field.NewInt64(table, "attr_id")
	p.AttrName = field.NewString(table, "attr_name")
	p.AttrValue = field.NewString(table, "attr_value")
	p.AttrSort = field.NewInt32(table, "attr_sort")
	p.QuickShow = field.NewInt32(table, "quick_show")

	p.fillFieldMap()

	return p
}

func (p *pmsProductAttrValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pmsProductAttrValue) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["attr_id"] = p.AttrID
	p.fieldMap["attr_name"] = p.AttrName
	p.fieldMap["attr_value"] = p.AttrValue
	p.fieldMap["attr_sort"] = p.AttrSort
	p.fieldMap["quick_show"] = p.QuickShow
}

func (p pmsProductAttrValue) clone(db *gorm.DB) pmsProductAttrValue {
	p.pmsProductAttrValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pmsProductAttrValue) replaceDB(db *gorm.DB) pmsProductAttrValue {
	p.pmsProductAttrValueDo.ReplaceDB(db)
	return p
}

type pmsProductAttrValueDo struct{ gen.DO }

func (p pmsProductAttrValueDo) Debug() *pmsProductAttrValueDo {
	return p.withDO(p.DO.Debug())
}

func (p pmsProductAttrValueDo) WithContext(ctx context.Context) *pmsProductAttrValueDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pmsProductAttrValueDo) ReadDB() *pmsProductAttrValueDo {
	return p.Clauses(dbresolver.Read)
}

func (p pmsProductAttrValueDo) WriteDB() *pmsProductAttrValueDo {
	return p.Clauses(dbresolver.Write)
}

func (p pmsProductAttrValueDo) Session(config *gorm.Session) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Session(config))
}

func (p pmsProductAttrValueDo) Clauses(conds ...clause.Expression) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pmsProductAttrValueDo) Returning(value interface{}, columns ...string) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pmsProductAttrValueDo) Not(conds ...gen.Condition) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pmsProductAttrValueDo) Or(conds ...gen.Condition) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pmsProductAttrValueDo) Select(conds ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pmsProductAttrValueDo) Where(conds ...gen.Condition) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pmsProductAttrValueDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *pmsProductAttrValueDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p pmsProductAttrValueDo) Order(conds ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pmsProductAttrValueDo) Distinct(cols ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pmsProductAttrValueDo) Omit(cols ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pmsProductAttrValueDo) Join(table schema.Tabler, on ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pmsProductAttrValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pmsProductAttrValueDo) RightJoin(table schema.Tabler, on ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pmsProductAttrValueDo) Group(cols ...field.Expr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pmsProductAttrValueDo) Having(conds ...gen.Condition) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pmsProductAttrValueDo) Limit(limit int) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pmsProductAttrValueDo) Offset(offset int) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pmsProductAttrValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pmsProductAttrValueDo) Unscoped() *pmsProductAttrValueDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pmsProductAttrValueDo) Create(values ...*model.PmsProductAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pmsProductAttrValueDo) CreateInBatches(values []*model.PmsProductAttrValue, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pmsProductAttrValueDo) Save(values ...*model.PmsProductAttrValue) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pmsProductAttrValueDo) First() (*model.PmsProductAttrValue, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsProductAttrValue), nil
	}
}

func (p pmsProductAttrValueDo) Take() (*model.PmsProductAttrValue, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsProductAttrValue), nil
	}
}

func (p pmsProductAttrValueDo) Last() (*model.PmsProductAttrValue, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsProductAttrValue), nil
	}
}

func (p pmsProductAttrValueDo) Find() ([]*model.PmsProductAttrValue, error) {
	result, err := p.DO.Find()
	return result.([]*model.PmsProductAttrValue), err
}

func (p pmsProductAttrValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PmsProductAttrValue, err error) {
	buf := make([]*model.PmsProductAttrValue, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pmsProductAttrValueDo) FindInBatches(result *[]*model.PmsProductAttrValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pmsProductAttrValueDo) Attrs(attrs ...field.AssignExpr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pmsProductAttrValueDo) Assign(attrs ...field.AssignExpr) *pmsProductAttrValueDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pmsProductAttrValueDo) Joins(fields ...field.RelationField) *pmsProductAttrValueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pmsProductAttrValueDo) Preload(fields ...field.RelationField) *pmsProductAttrValueDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pmsProductAttrValueDo) FirstOrInit() (*model.PmsProductAttrValue, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsProductAttrValue), nil
	}
}

func (p pmsProductAttrValueDo) FirstOrCreate() (*model.PmsProductAttrValue, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsProductAttrValue), nil
	}
}

func (p pmsProductAttrValueDo) FindByPage(offset int, limit int) (result []*model.PmsProductAttrValue, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pmsProductAttrValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pmsProductAttrValueDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pmsProductAttrValueDo) Delete(models ...*model.PmsProductAttrValue) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pmsProductAttrValueDo) withDO(do gen.Dao) *pmsProductAttrValueDo {
	p.DO = *do.(*gen.DO)
	return p
}
