// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gulimall-product/internal/gulimall_product/model"
)

func newPmsCommentReplay(db *gorm.DB, opts ...gen.DOOption) pmsCommentReplay {
	_pmsCommentReplay := pmsCommentReplay{}

	_pmsCommentReplay.pmsCommentReplayDo.UseDB(db, opts...)
	_pmsCommentReplay.pmsCommentReplayDo.UseModel(&model.PmsCommentReplay{})

	tableName := _pmsCommentReplay.pmsCommentReplayDo.TableName()
	_pmsCommentReplay.ALL = field.NewAsterisk(tableName)
	_pmsCommentReplay.ID = field.NewInt64(tableName, "id")
	_pmsCommentReplay.CommentID = field.NewInt64(tableName, "comment_id")
	_pmsCommentReplay.ReplyID = field.NewInt64(tableName, "reply_id")

	_pmsCommentReplay.fillFieldMap()

	return _pmsCommentReplay
}

type pmsCommentReplay struct {
	pmsCommentReplayDo

	ALL       field.Asterisk
	ID        field.Int64 // id
	CommentID field.Int64 // 评论id
	ReplyID   field.Int64 // 回复id

	fieldMap map[string]field.Expr
}

func (p pmsCommentReplay) Table(newTableName string) *pmsCommentReplay {
	p.pmsCommentReplayDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pmsCommentReplay) As(alias string) *pmsCommentReplay {
	p.pmsCommentReplayDo.DO = *(p.pmsCommentReplayDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pmsCommentReplay) updateTableName(table string) *pmsCommentReplay {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.CommentID = field.NewInt64(table, "comment_id")
	p.ReplyID = field.NewInt64(table, "reply_id")

	p.fillFieldMap()

	return p
}

func (p *pmsCommentReplay) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pmsCommentReplay) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["comment_id"] = p.CommentID
	p.fieldMap["reply_id"] = p.ReplyID
}

func (p pmsCommentReplay) clone(db *gorm.DB) pmsCommentReplay {
	p.pmsCommentReplayDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pmsCommentReplay) replaceDB(db *gorm.DB) pmsCommentReplay {
	p.pmsCommentReplayDo.ReplaceDB(db)
	return p
}

type pmsCommentReplayDo struct{ gen.DO }

func (p pmsCommentReplayDo) Debug() *pmsCommentReplayDo {
	return p.withDO(p.DO.Debug())
}

func (p pmsCommentReplayDo) WithContext(ctx context.Context) *pmsCommentReplayDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pmsCommentReplayDo) ReadDB() *pmsCommentReplayDo {
	return p.Clauses(dbresolver.Read)
}

func (p pmsCommentReplayDo) WriteDB() *pmsCommentReplayDo {
	return p.Clauses(dbresolver.Write)
}

func (p pmsCommentReplayDo) Session(config *gorm.Session) *pmsCommentReplayDo {
	return p.withDO(p.DO.Session(config))
}

func (p pmsCommentReplayDo) Clauses(conds ...clause.Expression) *pmsCommentReplayDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pmsCommentReplayDo) Returning(value interface{}, columns ...string) *pmsCommentReplayDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pmsCommentReplayDo) Not(conds ...gen.Condition) *pmsCommentReplayDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pmsCommentReplayDo) Or(conds ...gen.Condition) *pmsCommentReplayDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pmsCommentReplayDo) Select(conds ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pmsCommentReplayDo) Where(conds ...gen.Condition) *pmsCommentReplayDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pmsCommentReplayDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *pmsCommentReplayDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p pmsCommentReplayDo) Order(conds ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pmsCommentReplayDo) Distinct(cols ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pmsCommentReplayDo) Omit(cols ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pmsCommentReplayDo) Join(table schema.Tabler, on ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pmsCommentReplayDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pmsCommentReplayDo) RightJoin(table schema.Tabler, on ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pmsCommentReplayDo) Group(cols ...field.Expr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pmsCommentReplayDo) Having(conds ...gen.Condition) *pmsCommentReplayDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pmsCommentReplayDo) Limit(limit int) *pmsCommentReplayDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pmsCommentReplayDo) Offset(offset int) *pmsCommentReplayDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pmsCommentReplayDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pmsCommentReplayDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pmsCommentReplayDo) Unscoped() *pmsCommentReplayDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pmsCommentReplayDo) Create(values ...*model.PmsCommentReplay) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pmsCommentReplayDo) CreateInBatches(values []*model.PmsCommentReplay, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pmsCommentReplayDo) Save(values ...*model.PmsCommentReplay) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pmsCommentReplayDo) First() (*model.PmsCommentReplay, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsCommentReplay), nil
	}
}

func (p pmsCommentReplayDo) Take() (*model.PmsCommentReplay, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsCommentReplay), nil
	}
}

func (p pmsCommentReplayDo) Last() (*model.PmsCommentReplay, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsCommentReplay), nil
	}
}

func (p pmsCommentReplayDo) Find() ([]*model.PmsCommentReplay, error) {
	result, err := p.DO.Find()
	return result.([]*model.PmsCommentReplay), err
}

func (p pmsCommentReplayDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PmsCommentReplay, err error) {
	buf := make([]*model.PmsCommentReplay, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pmsCommentReplayDo) FindInBatches(result *[]*model.PmsCommentReplay, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pmsCommentReplayDo) Attrs(attrs ...field.AssignExpr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pmsCommentReplayDo) Assign(attrs ...field.AssignExpr) *pmsCommentReplayDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pmsCommentReplayDo) Joins(fields ...field.RelationField) *pmsCommentReplayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pmsCommentReplayDo) Preload(fields ...field.RelationField) *pmsCommentReplayDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pmsCommentReplayDo) FirstOrInit() (*model.PmsCommentReplay, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsCommentReplay), nil
	}
}

func (p pmsCommentReplayDo) FirstOrCreate() (*model.PmsCommentReplay, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsCommentReplay), nil
	}
}

func (p pmsCommentReplayDo) FindByPage(offset int, limit int) (result []*model.PmsCommentReplay, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pmsCommentReplayDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pmsCommentReplayDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pmsCommentReplayDo) Delete(models ...*model.PmsCommentReplay) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pmsCommentReplayDo) withDO(do gen.Dao) *pmsCommentReplayDo {
	p.DO = *do.(*gen.DO)
	return p
}
