// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gulimall-product/internal/gulimall_product/model"
)

func newPmsSpuInfoDesc(db *gorm.DB, opts ...gen.DOOption) pmsSpuInfoDesc {
	_pmsSpuInfoDesc := pmsSpuInfoDesc{}

	_pmsSpuInfoDesc.pmsSpuInfoDescDo.UseDB(db, opts...)
	_pmsSpuInfoDesc.pmsSpuInfoDescDo.UseModel(&model.PmsSpuInfoDesc{})

	tableName := _pmsSpuInfoDesc.pmsSpuInfoDescDo.TableName()
	_pmsSpuInfoDesc.ALL = field.NewAsterisk(tableName)
	_pmsSpuInfoDesc.SpuID = field.NewInt64(tableName, "spu_id")
	_pmsSpuInfoDesc.Decript = field.NewString(tableName, "decript")

	_pmsSpuInfoDesc.fillFieldMap()

	return _pmsSpuInfoDesc
}

type pmsSpuInfoDesc struct {
	pmsSpuInfoDescDo

	ALL     field.Asterisk
	SpuID   field.Int64  // 商品id
	Decript field.String // 商品介绍

	fieldMap map[string]field.Expr
}

func (p pmsSpuInfoDesc) Table(newTableName string) *pmsSpuInfoDesc {
	p.pmsSpuInfoDescDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pmsSpuInfoDesc) As(alias string) *pmsSpuInfoDesc {
	p.pmsSpuInfoDescDo.DO = *(p.pmsSpuInfoDescDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pmsSpuInfoDesc) updateTableName(table string) *pmsSpuInfoDesc {
	p.ALL = field.NewAsterisk(table)
	p.SpuID = field.NewInt64(table, "spu_id")
	p.Decript = field.NewString(table, "decript")

	p.fillFieldMap()

	return p
}

func (p *pmsSpuInfoDesc) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pmsSpuInfoDesc) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["spu_id"] = p.SpuID
	p.fieldMap["decript"] = p.Decript
}

func (p pmsSpuInfoDesc) clone(db *gorm.DB) pmsSpuInfoDesc {
	p.pmsSpuInfoDescDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pmsSpuInfoDesc) replaceDB(db *gorm.DB) pmsSpuInfoDesc {
	p.pmsSpuInfoDescDo.ReplaceDB(db)
	return p
}

type pmsSpuInfoDescDo struct{ gen.DO }

func (p pmsSpuInfoDescDo) Debug() *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Debug())
}

func (p pmsSpuInfoDescDo) WithContext(ctx context.Context) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pmsSpuInfoDescDo) ReadDB() *pmsSpuInfoDescDo {
	return p.Clauses(dbresolver.Read)
}

func (p pmsSpuInfoDescDo) WriteDB() *pmsSpuInfoDescDo {
	return p.Clauses(dbresolver.Write)
}

func (p pmsSpuInfoDescDo) Session(config *gorm.Session) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Session(config))
}

func (p pmsSpuInfoDescDo) Clauses(conds ...clause.Expression) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pmsSpuInfoDescDo) Returning(value interface{}, columns ...string) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pmsSpuInfoDescDo) Not(conds ...gen.Condition) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pmsSpuInfoDescDo) Or(conds ...gen.Condition) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pmsSpuInfoDescDo) Select(conds ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pmsSpuInfoDescDo) Where(conds ...gen.Condition) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pmsSpuInfoDescDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *pmsSpuInfoDescDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p pmsSpuInfoDescDo) Order(conds ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pmsSpuInfoDescDo) Distinct(cols ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pmsSpuInfoDescDo) Omit(cols ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pmsSpuInfoDescDo) Join(table schema.Tabler, on ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pmsSpuInfoDescDo) LeftJoin(table schema.Tabler, on ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pmsSpuInfoDescDo) RightJoin(table schema.Tabler, on ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pmsSpuInfoDescDo) Group(cols ...field.Expr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pmsSpuInfoDescDo) Having(conds ...gen.Condition) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pmsSpuInfoDescDo) Limit(limit int) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pmsSpuInfoDescDo) Offset(offset int) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pmsSpuInfoDescDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pmsSpuInfoDescDo) Unscoped() *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pmsSpuInfoDescDo) Create(values ...*model.PmsSpuInfoDesc) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pmsSpuInfoDescDo) CreateInBatches(values []*model.PmsSpuInfoDesc, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pmsSpuInfoDescDo) Save(values ...*model.PmsSpuInfoDesc) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pmsSpuInfoDescDo) First() (*model.PmsSpuInfoDesc, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsSpuInfoDesc), nil
	}
}

func (p pmsSpuInfoDescDo) Take() (*model.PmsSpuInfoDesc, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsSpuInfoDesc), nil
	}
}

func (p pmsSpuInfoDescDo) Last() (*model.PmsSpuInfoDesc, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsSpuInfoDesc), nil
	}
}

func (p pmsSpuInfoDescDo) Find() ([]*model.PmsSpuInfoDesc, error) {
	result, err := p.DO.Find()
	return result.([]*model.PmsSpuInfoDesc), err
}

func (p pmsSpuInfoDescDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PmsSpuInfoDesc, err error) {
	buf := make([]*model.PmsSpuInfoDesc, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pmsSpuInfoDescDo) FindInBatches(result *[]*model.PmsSpuInfoDesc, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pmsSpuInfoDescDo) Attrs(attrs ...field.AssignExpr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pmsSpuInfoDescDo) Assign(attrs ...field.AssignExpr) *pmsSpuInfoDescDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pmsSpuInfoDescDo) Joins(fields ...field.RelationField) *pmsSpuInfoDescDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pmsSpuInfoDescDo) Preload(fields ...field.RelationField) *pmsSpuInfoDescDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pmsSpuInfoDescDo) FirstOrInit() (*model.PmsSpuInfoDesc, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsSpuInfoDesc), nil
	}
}

func (p pmsSpuInfoDescDo) FirstOrCreate() (*model.PmsSpuInfoDesc, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PmsSpuInfoDesc), nil
	}
}

func (p pmsSpuInfoDescDo) FindByPage(offset int, limit int) (result []*model.PmsSpuInfoDesc, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pmsSpuInfoDescDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pmsSpuInfoDescDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pmsSpuInfoDescDo) Delete(models ...*model.PmsSpuInfoDesc) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pmsSpuInfoDescDo) withDO(do gen.Dao) *pmsSpuInfoDescDo {
	p.DO = *do.(*gen.DO)
	return p
}
