// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsBrand = "pms_brand"

// PmsBrand mapped from table <pms_brand>
type PmsBrand struct {
	BrandID     int64  `gorm:"column:brand_id;primaryKey;autoIncrement:true;comment:品牌id" json:"brand_id"`
	Name        string `gorm:"column:name;comment:品牌名" json:"name"`
	Logo        string `gorm:"column:logo;comment:品牌logo地址" json:"logo"`
	Descript    string `gorm:"column:descript;comment:介绍" json:"descript"`
	ShowStatus  int32  `gorm:"column:show_status;comment:显示状态[0-不显示；1-显示]" json:"show_status"`
	FirstLetter string `gorm:"column:first_letter;comment:检索首字母" json:"first_letter"`
	Sort        int32  `gorm:"column:sort;comment:排序" json:"sort"`
}

// TableName PmsBrand's table name
func (*PmsBrand) TableName() string {
	return TableNamePmsBrand
}
