// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsSkuInfo = "pms_sku_info"

// PmsSkuInfo mapped from table <pms_sku_info>
type PmsSkuInfo struct {
	SkuID         int64   `gorm:"column:sku_id;primaryKey;autoIncrement:true;comment:skuId" json:"sku_id"`
	SpuID         int64   `gorm:"column:spu_id;comment:spuId" json:"spu_id"`
	SkuName       string  `gorm:"column:sku_name;comment:sku名称" json:"sku_name"`
	SkuDesc       string  `gorm:"column:sku_desc;comment:sku介绍描述" json:"sku_desc"`
	CatalogID     int64   `gorm:"column:catalog_id;comment:所属分类id" json:"catalog_id"`
	BrandID       int64   `gorm:"column:brand_id;comment:品牌id" json:"brand_id"`
	SkuDefaultImg string  `gorm:"column:sku_default_img;comment:默认图片" json:"sku_default_img"`
	SkuTitle      string  `gorm:"column:sku_title;comment:标题" json:"sku_title"`
	SkuSubtitle   string  `gorm:"column:sku_subtitle;comment:副标题" json:"sku_subtitle"`
	Price         float64 `gorm:"column:price;comment:价格" json:"price"`
	SaleCount     int64   `gorm:"column:sale_count;comment:销量" json:"sale_count"`
}

// TableName PmsSkuInfo's table name
func (*PmsSkuInfo) TableName() string {
	return TableNamePmsSkuInfo
}
