// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePmsSpuInfo = "pms_spu_info"

// PmsSpuInfo mapped from table <pms_spu_info>
type PmsSpuInfo struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:商品id" json:"id"`
	SpuName        string    `gorm:"column:spu_name;comment:商品名称" json:"spu_name"`
	SpuDescription string    `gorm:"column:spu_description;comment:商品描述" json:"spu_description"`
	CatalogID      int64     `gorm:"column:catalog_id;comment:所属分类id" json:"catalog_id"`
	BrandID        int64     `gorm:"column:brand_id;comment:品牌id" json:"brand_id"`
	Weight         float64   `gorm:"column:weight" json:"weight"`
	PublishStatus  int32     `gorm:"column:publish_status;comment:上架状态[0 - 下架，1 - 上架]" json:"publish_status"`
	CreateTime     time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName PmsSpuInfo's table name
func (*PmsSpuInfo) TableName() string {
	return TableNamePmsSpuInfo
}
