// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsAttrAttrgroupRelation = "pms_attr_attrgroup_relation"

// PmsAttrAttrgroupRelation mapped from table <pms_attr_attrgroup_relation>
type PmsAttrAttrgroupRelation struct {
	ID          int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	AttrID      int64 `gorm:"column:attr_id;comment:属性id" json:"attr_id"`
	AttrGroupID int64 `gorm:"column:attr_group_id;comment:属性分组id" json:"attr_group_id"`
	AttrSort    int32 `gorm:"column:attr_sort;comment:属性组内排序" json:"attr_sort"`
}

// TableName PmsAttrAttrgroupRelation's table name
func (*PmsAttrAttrgroupRelation) TableName() string {
	return TableNamePmsAttrAttrgroupRelation
}
