// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsCommentReplay = "pms_comment_replay"

// PmsCommentReplay mapped from table <pms_comment_replay>
type PmsCommentReplay struct {
	ID        int64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	CommentID int64 `gorm:"column:comment_id;comment:评论id" json:"comment_id"`
	ReplyID   int64 `gorm:"column:reply_id;comment:回复id" json:"reply_id"`
}

// TableName PmsCommentReplay's table name
func (*PmsCommentReplay) TableName() string {
	return TableNamePmsCommentReplay
}
