// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsSpuImage = "pms_spu_images"

// PmsSpuImage mapped from table <pms_spu_images>
type PmsSpuImage struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	SpuID      int64  `gorm:"column:spu_id;comment:spu_id" json:"spu_id"`
	ImgName    string `gorm:"column:img_name;comment:图片名" json:"img_name"`
	ImgURL     string `gorm:"column:img_url;comment:图片地址" json:"img_url"`
	ImgSort    int32  `gorm:"column:img_sort;comment:顺序" json:"img_sort"`
	DefaultImg int32  `gorm:"column:default_img;comment:是否默认图" json:"default_img"`
}

// TableName PmsSpuImage's table name
func (*PmsSpuImage) TableName() string {
	return TableNamePmsSpuImage
}
