// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsCategory = "pms_category"

// PmsCategory mapped from table <pms_category>
type PmsCategory struct {
	CatID        int64  `gorm:"column:cat_id;primaryKey;autoIncrement:true;comment:分类id" json:"cat_id"`
	Name         string `gorm:"column:name;comment:分类名称" json:"name"`
	ParentCid    int64  `gorm:"column:parent_cid;comment:父分类id" json:"parent_cid"`
	CatLevel     int32  `gorm:"column:cat_level;comment:层级" json:"cat_level"`
	ShowStatus   int32  `gorm:"column:show_status;comment:是否显示[0-不显示，1显示]" json:"show_status"`
	Sort         int32  `gorm:"column:sort;comment:排序" json:"sort"`
	Icon         string `gorm:"column:icon;comment:图标地址" json:"icon"`
	ProductUnit  string `gorm:"column:product_unit;comment:计量单位" json:"product_unit"`
	ProductCount int32  `gorm:"column:product_count;comment:商品数量" json:"product_count"`
}

// TableName PmsCategory's table name
func (*PmsCategory) TableName() string {
	return TableNamePmsCategory
}
